version: "3.8"
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://localhost:8000"
    ports:
      # inside container serve runs on 5000
      - "3000:5000"
    depends_on:
      - backend
